### ISSUE TITLE
Confused with the demo source + structuring with Node & Express backend

### ISSUE THREAD

**Issue by patrickbolle** [websanova/vue-auth#29]
Hi there, really excited to start using this - it's exactly what I need.

I've got a Node backend with Express + RethinkDB using Passport JS for server-side authentication.

How exactly would I implement this plugin with that?
I tried to look into your demo server source but I don't use Laravel so that looks like a total mess to me sadly.

For example, I've got my /login and /register route on the server like this - 
```
app.post('/signup', function(req, res) {
	var user = new User({
		email: req.query.email,
		password: req.query.password
	});
	user.save().then(function(result) {
		res.send(result);
		console.log("Worked");
	}).error(handleError(res));
});
```
```
app.post('/login', passport.authenticate('local'), function(req, res) {
	res.json({ loggedin: true });
	console.log(res);
});
```

In your demo code for login, you are calling this $auth property like this - 
```
login() {
                this.$auth.login({
                    body: this.data.body,
                    rememberMe: this.data.rememberMe,
                    redirect: {name: 'account'},
                    success() {
                        console.log('success ' + this.context);
                    },
                    error(res) {
                        console.log('error ' + this.context);
                        this.error = res.data;
                    }
                });
            }
```
How does the plugin know to go to /login route or /signup or /register or whatever the route may be?
I know we initialize in the HTTP route in the app.js like this:
```
Vue.http.options.root = 'https://api-demo.websanova.com/api/v1';
```
but I'm confused after that point.

Any pointers would be greatly appreciated, thanks so much.

**Comment by websanova** [comment]
Check the docs on GitHub for one.

Also, I guess in express you are using query, but should be body sine it's
post call. Unless you changed it to get.

**Comment by patrickbolle** [comment]
Hey, thanks. Yeah I'm going through the docs line by line right now. 
I guess I will be assigning with this - 
```
loginData: {url: 'auth/login', method: 'POST', redirect: '/'}

```
Where my login route should go?
That would make sense.

I'm not too sure why the express call is .query instead of .body I was sending requests through Postman and .body wasn't working, I'll try and figure that out. Thanks!

**Comment by websanova** [comment]
Ya, not sure if it's body or not, but I think there were some different fields

**Comment by patrickbolle** [comment]
Hi @websanova . I've got a question about the automatic calling of /auth/user .
I've got login + register working, but after login,  GET /auth/user is called on its own.
I created the route on my server to grab the user info, but there is nothing useful being sent in the req to /auth/user. 
When i console.log(req) on my server I get the full request (including Bearer auth id, session id, etc) but nothing specifically identifying the user.

On /auth/user route I was hoping to grab all user data WHERE email = req.body.email or something similar.
Am I missing something here? Would love some pointers.

Thanks a bunch!

**Comment by websanova** [comment]
There is an Authorization header, try grabbing that.

**Comment by patrickbolle** [comment]
Is that something that I should be storing in the database with the user? Like it is a single authorization ID per user for example?
Sorry, I'm a bit of a noob when it comes to this stuff!
Cheeers.

**Comment by websanova** [comment]
Well.... Really depends on the scheme. MYbe try reading up on jwt (json web
tokens) or single page auth with tokens. I would imagine there is some
library for node already.

**Comment by patrickbolle** [comment]
@websanova Got it figured out, thanks.
I'm having a problem after login - 

The following code works fine after login : 
```
      <a v-if="$auth.check()" v-link="'/secret'" class="nav-item">
        Secret Page
      </a>
```
On the same component though, this does NOT work : 
```
        {{ $auth.user().id }}
```
I get this error in console - 
```
Error when evaluating expression "$auth.user().id": TypeError: scope.$auth.user(...) is undefined (found in component: <navbar>)
```

**Comment by websanova** [comment]
Is the `$auth.user()` inside the` $auth.check()` or outside?

**Comment by websanova** [comment]
Also, after login, can you try to log the `this.$auth.user()` and see
what's there.

Also what version of vue, vue-router, vue-resource, etc do you have? (need
to make sure it's latest for 1.x).

**Comment by patrickbolle** [comment]
@websanova $auth.user() is outside the auth check. here's the actual layout of the file -
```
      <a class="nav-item" href="#" >
        {{ $auth.user().id }}
      </a>
      <a class="nav-item" href="/">
        Home
      </a>
      <a class="nav-item" v-if="!$auth.check()" v-link="'/login'">
        Login
      </a>
```
In my login component here - 
```
      this.$auth.login({
          body: this.body,
          redirect: '/',
          success: function () { console.log(this.$auth.user()); },
          error: function () { console.log("AUTH FAILURE BOOOOO"); },
          rememberMe: true,
      });
```
the console.log(this.$auth.user()) returns 'undefined'.

As for versions:
    "vue": "^1.0.21",
    "vue-resource": "^1.0.2",
    "vue-router": "^0.7.13"
    "@websanova/vue-auth": "^1.0.9-dev",

Thanks!

**Comment by websanova** [comment]
Right. so if you're not logged in, there is no data.

I suppose it can return an empty object, at least it won't throw the error
then...

**Comment by websanova** [comment]
I've pushed up vue-auth 1.0.10-dev. It will return an empty object instead
of undefined now.

**Comment by patrickbolle** [comment]
Okay wonderful.So essentially what you are saying is that my user is not logged in?

**Comment by patrickbolle** [comment]
@websanova Yeah, updated to 1.0.10-dev and now get an empty object!
But yeah now I'm confused as to... why I'm getting the empty object I guess. My /auth/user is returning the user object in the response. 
```
		return res.json({ success: true, user: user.email });
```
Is this what the $auth.user is looking for? I'm still getting an empty object

**Comment by websanova** [comment]
Read the docs ;)

**Comment by websanova** [comment]
The plugin doesn't know you're returning at as user.... default is data
